spring:
  datasource:
    #   数据源基本配置
    username: root
    password: yyy123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.179.174:3306/yingqin?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    jedis:
      pool:
        max-active: 5
    password:
    host: 39.97.179.174
    port: 6379
    database: 0
  mail:
    password: ruraqyuogkwobeig
    host: smtp.qq.com
    username: 971773196@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:MybatisConfig.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mappers/*.xml
email:
  title: 您正在进行验证操作
  text: 若不是您本人操作,请忽略此消息,您的验证码为：
  fromUser: 971773196@qq.com
server:
  port: 8081